services:
  db:
    image: postgres:15-alpine
    container_name: task_postgres
    restart: always
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: task_fastapi
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8000"
    volumes:
      - ./app:/code/app

volumes:
  postgres_data: